sudo: required
env:
  DOCKER_COMPOSE_VERSION: 1.13.0

addons:
  apt:
    packages:
    - net-tools
    - openvpn

#services:
#- docker

#before_install:
#- docker info
#- sudo apt-get remove docker docker-engine
#- sudo apt-get update
#- sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual apt-transport-https ca-certificates curl software-properties-common
#- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#- sudo apt-get update
#- sudo apt-get install docker-ce
#- docker info
#- sudo rm /usr/local/bin/docker-compose
#- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#- chmod +x docker-compose
#- sudo mv docker-compose /usr/local/bin

#before_script:
#- env PORTAL_VERSION="${TRAVIS_TAG:-$TRAVIS_COMMIT}" docker-compose -f dev.yml up -d --build portal
#- docker-compose -f dev.yml exec portal bash /etc/ckan_init.d/tests/install_nodejs.sh
#- docker-compose -f dev.yml exec portal bash /etc/ckan_init.d/tests/install_solr4.sh

script:
#- docker-compose -f dev.yml exec portal bash -c 'su -c "bash /etc/ckan_init.d/tests/run_all_tests.sh" -l $USER'
- pwd

deploy:
#- provider: script
#  skip_cleanup: true
#  script: "scripts/upload.sh $TRAVIS_TAG"
#  on:
#    tags: true
#    condition: "$TRAVIS_TAG =~ ^release-.*"
#- provider: script
#  skip_cleanup: true
#  script: "scripts/run_deploy.sh latest testing"
#  on:
#    branch: master
- provider: script
  skip_cleanup: true
  script: "scripts/test_vpn.sh datosgobar-dev && scripts/test_vpn.sh andino-dev"
  on:
    branch: 108-Actualizar-CD-de-development-para-ambientes-nuevos

git:
  depth:
     1
