sudo: required

services:
  - docker

before_install:
  - docker-compose -f dev.yml up -d --build portal
  - docker-compose -f dev.yml exec portal bash /etc/ckan_init.d/tests/install_solr4.sh
  - docker-compose -f dev.yml exec portal bash /etc/ckan_init.d/tests/install_nodejs.sh

script:
  - docker-compose -f dev.yml exec portal bash -c 'su -c "bash /etc/ckan_init.d/tests/run_all_tests.sh" -l $USER'

deploy:
  provider: script
  skip_cleanup: true
  script: "deploy/update_testing.sh"